on: [ push ]

jobs:
  my-job:
    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v2
    - name: Run the action
      id: Hello
      uses: ./
      with:
        myInput: 'Chad Crowell'
    - name: output
      run: |
        echo ${{steps.hello.outputs.memory }}
        echo " total memory previewed "
